# Site settings
author: Samantha Sanford
title: Flatiron Software Engineering Program
header-img: img/home-bg.png
email: samanthawebdev@gmail.com
copyright_name: Samantha Sanford
description: > # this means to ignore newlines until "baseurl:"
  Documenting my progress!
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  samanthasanford

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
